INSERT INTO actors (id, id_film, actor_name) VALUES (1, 1, 'Michael Fassbender');
INSERT INTO actors (id, id_film, actor_name) VALUES (2, 1, 'Katherine Waterston');
INSERT INTO actors (id, id_film, actor_name) VALUES (3, 1, 'Weaver''s Ellen Ripley');
INSERT INTO actors (id, id_film, actor_name) VALUES (4, 2, 'Tom Everett Scott');
INSERT INTO actors (id, id_film, actor_name) VALUES (5, 2, 'Alicia Silverstone');
INSERT INTO actors (id, id_film, actor_name) VALUES (6, 3, 'Charlie Hunnam');
INSERT INTO actors (id, id_film, actor_name) VALUES (10, 3, 'Djimon Hounsou');
INSERT INTO actors (id, id_film, actor_name) VALUES (11, 3, 'Aidan Gillen');
INSERT INTO actors (id, id_film, actor_name) VALUES (12, 3, 'Jude Law');
INSERT INTO actors (id, id_film, actor_name) VALUES (13, 3, 'Eric Bana');
INSERT INTO actors (id, id_film, actor_name) VALUES (7, 3, 'Kingsley Ben-Adir');
INSERT INTO actors (id, id_film, actor_name) VALUES (8, 5, 'Prabhas');
INSERT INTO actors (id, id_film, actor_name) VALUES (14, 5, 'Rana Daggubati');
INSERT INTO actors (id, id_film, actor_name) VALUES (15, 5, 'Anushka Shetty');
INSERT INTO actors (id, id_film, actor_name) VALUES (16, 5, 'Ramya Krishnan');
INSERT INTO actors (id, id_film, actor_name) VALUES (17, 5, 'Sathyaraj');
INSERT INTO actors (id, id_film, actor_name) VALUES (18, 11, 'Chris Pratt');
INSERT INTO actors (id, id_film, actor_name) VALUES (19, 11, 'Zoe Saldana');
INSERT INTO actors (id, id_film, actor_name) VALUES (20, 11, 'Dave Bautista');
INSERT INTO actors (id, id_film, actor_name) VALUES (21, 11, 'Vin Diesel');
INSERT INTO actors (id, id_film, actor_name) VALUES (22, 11, 'Bradley Cooper');
INSERT INTO actors (id, id_film, actor_name) VALUES (23, 11, 'Michael Rooker');
INSERT INTO actors (id, id_film, actor_name) VALUES (24, 11, 'Karen Gillan');
INSERT INTO actors (id, id_film, actor_name) VALUES (25, 4, 'Bryan Cranston');
INSERT INTO actors (id, id_film, actor_name) VALUES (26, 4, 'Jennifer Garner');
INSERT INTO actors (id, id_film, actor_name) VALUES (27, 4, 'Beverly D''Angelo');