INSERT INTO genres (id, id_film, genre) VALUES (2, 2, 'Comedy');
INSERT INTO genres (id, id_film, genre) VALUES (9, 2, 'Family');
INSERT INTO genres (id, id_film, genre) VALUES (4, 3, 'Drama ');
INSERT INTO genres (id, id_film, genre) VALUES (7, 5, 'Fantasy');
INSERT INTO genres (id, id_film, genre) VALUES (10, 3, 'Fantasy');
INSERT INTO genres (id, id_film, genre) VALUES (5, 4, 'Drama');
INSERT INTO genres (id, id_film, genre) VALUES (11, 5, 'Drama');
INSERT INTO genres (id, id_film, genre) VALUES (12, 11, 'Fantasy');
INSERT INTO genres (id, id_film, genre) VALUES (13, 11, 'Comedy');
INSERT INTO genres (id, id_film, genre) VALUES (3, 1, 'Triller');
INSERT INTO genres (id, id_film, genre) VALUES (1, 1, 'Horror');
INSERT INTO genres (id, id_film, genre) VALUES (14, 11, 'Action');